apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: ecs-service-broker-instance
  namespace: default
spec:
  # References one of the previously returned services
  clusterServiceClassExternalName: ecs-bucket
  clusterServicePlanExternalName: 5gb
  #####
  # Additional parameters can be added here,
  # which may be used by the service broker.
  #####