apiVersion: v1
kind: Pod
metadata:
  name: broker-test-app
spec:
  containers:
  - name: broker-test-app
    image: svistunovaleksandr/test-repo:broker-test-app
    imagePullPolicy: Always
    ports:
    - name: web
      containerPort: 8080
      protocol: TCP
    env:
    - name: "ENDPOINT"
      valueFrom:
        secretKeyRef:
          name: ecs-service-broker-binding
          key: endpoint
    - name: "ACCESS_KEY"
      valueFrom:
        secretKeyRef:
          name: ecs-service-broker-binding
          key: accessKey
    - name: "SECRET_KEY"
      valueFrom:
        secretKeyRef:
          name: ecs-service-broker-binding
          key: secretKey
    - name: "BUCKET"
      valueFrom:
        secretKeyRef:
          name: ecs-service-broker-binding
          key: bucket
