---
platform: linux

image_resource:
  type: docker-image
  source: {repository: bash}

params:
  DEBUG:
  OUTPUT_FILE_NAME:
  PARAM_NAME:

outputs:
  - name: output-folder

run:
  path: /usr/local/bin/bash
  args:
    - -c
    - |
      if [[ $DEBUG == true ]]; then
        set -ex
      else
        set -e
      fi

      echo "$PARAM_NAME" > output-folder/$OUTPUT_FILE_NAME
