apiVersion: v1
kind: Pod
metadata:
  name: ecs-broker-test
spec:
  containers:
    - name: ecs-broker
      image: objectscale/ecs-service-broker:latest
      command: [ "java","-jar","-Djava.security.egd=file:/dev/./urandom","app.jar", "-Dspring.config.location=/etc/config/application.yml" ]
      volumeMounts:
      - name: config-volume
        mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: ecs-broker
  restartPolicy: Never
