platform: linux

image_resource:
  type: registry-image
  source:
    repository: alpine

params:
  VERSION:
  DEBUG:
  BRANCH:

inputs:
  - name: project-repo

outputs:
  - name: generated_tag

run:
  path: project-repo/ci/tasks/generate-tag/task.sh