---
resource_types:

  - name: slack-notifier
    type: docker-image
    source:
      repository: mockersf/concourse-slack-notifier

resources:

  - name: ecs-broker-repo
    type: git
    source:
      uri: ((broker_repo))
      branch: ((broker_branch))
      access_token: ((git_token))
      ignore_paths:
        - manifest.yml.default
        - skaffold.yaml
        - .travis.yml
        - LICENSE
        - README.md
        - charts/**
        - kubernetes/**
        - gradle/**
        - ci/**
    check_every: 30m

  - name: docker_registry
    type: registry-image
    source:
      repository: ((custom_registry))
      debug: ((debug))

  - name: slack-alert
    type: slack-notifier
    source:
      url: ((slack_url))

jobs:

  - name: build-broker-docker-image
    plan:
      - get: ecs-broker-repo
        trigger: true

      - task: build-image
        privileged: true
        file: ecs-broker-repo/ci/tasks/build-image/task.yml
        input_mapping:
          project-repo: ecs-broker-repo
        output_mapping:
          image: broker-k8s-image
        params:
          DEBUG: ((debug))

      - task: generate-tag
        file: ecs-broker-repo/ci/tasks/generate-tag/task.yml
        input_mapping:
          project-repo: ecs-broker-repo
        output_mapping:
          generated_tag: broker-k8s-image-tag
        params:
          DEBUG: ((debug))
          VERSION: ((broker_version))
          BRANCH: ((broker_branch))

      - put: docker_registry
        params:
          image: broker-k8s-image/image.tar
          additional_tags: broker-k8s-image-tag/image_tag

    on_success:
      put: slack-alert
      params:
        alert_type: success

    on_failure:
      put: slack-alert
      params:
        alert_type: failed

    on_abort:
      put: slack-alert
      params:
        alert_type: aborted

    on_error:
      put: slack-alert
      params:
        alert_type: custom
        message: Build Error
